apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: kube-system
stringData:
  {{(index .SpecialResource.Spec.Configuration 0).Name}}: "{{(index (index .SpecialResource.Spec.Configuration 0).Value 0)}}"
  {{(index .SpecialResource.Spec.Configuration 1).Name}}: "{{(index (index .SpecialResource.Spec.Configuration 1).Value 0)}}"
