apiVersion: v1
entries:
  cert-manager:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-07-14T10:15:57.339642899Z"
    description: A recipe to install cert-manager via OLM
    digest: 75f3b4039799d6194bcc180758874974202dfbb9585990a11064896a4e2f7095
    icon: https://avatars.githubusercontent.com/u/55542927
    name: cert-manager
    type: application
    urls:
    - file:///charts/olm/cert-manager-0.0.1.tgz
    version: 0.0.1
generated: "2021-07-14T10:15:57.339334772Z"
