apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJxdWF5LmlvIjp7InVzZXJuYW1lIjoiZGFncmF5IiwicGFzc3dvcmQiOiJIM0BkUkB0UXVhIiwiZW1haWwiOiJtZUBoZXJlLmNvbSIsImF1dGgiOiJaR0ZuY21GNU9rZ3pRR1JTUUhSUmRXRT0ifX19
kind: Secret
metadata:
  name: {{.SpecialResource.Name}}-{{.GroupName.DriverContainer}}
type: kubernetes.io/dockerconfigjson
