apiVersion: sro.openshift.io/v1beta1
kind: SpecialResource
metadata:
  name: lustre-client
spec:
  namespace: lustre-client
  configuration:
    - name: "key_id"
      value: ["AWS_ACCESS_KEY_ID"]
    - name: "access_key"
      value: ["AWS_SECRET_ACCESS_KEY"]
  driverContainer:
    buildArgs:
      - name: "KVER"
        value: "{{.KernelFullVersion}}"
      - name: "RELEASEVER"
        value: "{{.OperatingSystemDecimal}}"

  dependsOn:
    - name: "driver-container-base"
      imageReference: "true"
